import type { Env } from "./types";
export async function getSettings(env:Env){
  const rows=await env.DB.prepare("SELECT key,value FROM settings").all<any>();
  const m=new Map((rows.results||[]).map((x:any)=>[x.key,x.value]));
  return{estimateUntimedEnabled:m.get("estimate_untimed_enabled")==="1",estimateUntimedHours:Number(m.get("estimate_untimed_hours")||6)};
}
export async function dashboard(env:Env){
  const cfg=await getSettings(env), est=cfg.estimateUntimedEnabled?cfg.estimateUntimedHours:0;
  const s=await env.DB.prepare(`SELECT COALESCE(SUM(quantity),0) totalAssignments,COALESCE(SUM(CASE WHEN status='open' THEN quantity ELSE 0 END),0) openSlots,COALESCE(SUM(CASE WHEN status='filled' THEN quantity ELSE 0 END),0) assignedSlots,COALESCE(SUM(CASE WHEN hours_known=0 THEN quantity ELSE 0 END),0) tbdAssignments,COALESCE(SUM(CASE WHEN hours_known=1 THEN hours*quantity ELSE 0 END),0) knownNeeded,COALESCE(SUM(CASE WHEN status='filled' AND hours_known=1 THEN hours*quantity ELSE 0 END),0) knownFilled,COALESCE(SUM(CASE WHEN hours_known=0 THEN quantity ELSE 0 END),0) tbdNeededQty,COALESCE(SUM(CASE WHEN status='filled' AND hours_known=0 THEN quantity ELSE 0 END),0) tbdFilledQty FROM volunteer_slots`).first<any>();
  const knownNeeded=Number(s?.knownNeeded||0),knownFilled=Number(s?.knownFilled||0),needed=knownNeeded+Number(s?.tbdNeededQty||0)*est,filled=knownFilled+Number(s?.tbdFilledQty||0)*est;
  const e=await env.DB.prepare(`SELECT e.id,e.signupgenius_id signupgeniusId,e.title,e.event_date eventDate,e.location,COALESCE(SUM(CASE WHEN v.hours_known=1 THEN v.hours*v.quantity ELSE 0 END),0) knownNeeded,COALESCE(SUM(CASE WHEN v.status='filled' AND v.hours_known=1 THEN v.hours*v.quantity ELSE 0 END),0) knownFilled,COALESCE(SUM(CASE WHEN v.hours_known=0 THEN v.quantity ELSE 0 END),0) tbdQty,COALESCE(SUM(CASE WHEN v.status='filled' AND v.hours_known=0 THEN v.quantity ELSE 0 END),0) tbdFilledQty,COALESCE(SUM(CASE WHEN v.status='open' THEN v.quantity ELSE 0 END),0) openSlots,COALESCE(SUM(CASE WHEN v.status='filled' THEN v.quantity ELSE 0 END),0) assignedSlots FROM events e LEFT JOIN volunteer_slots v ON v.event_id=e.id GROUP BY e.id ORDER BY e.event_date`).all<any>();
  const l=await env.DB.prepare("SELECT sync_time syncTime,status FROM sync_log ORDER BY id DESC LIMIT 1").first<any>();
  const cl=await env.DB.prepare("SELECT sync_time syncTime,status,message FROM contact_sync_log ORDER BY id DESC LIMIT 1").first<any>();
  const volunteers=await env.DB.prepare(`
    WITH cm AS (SELECT LOWER(email) email, COUNT(DISTINCT program) program_count, MIN(program) single_program FROM contact_mappings GROUP BY LOWER(email))
    SELECT COALESCE(NULLIF(v.volunteer_name,''),v.volunteer_email,'Unknown') name,v.volunteer_email email,
      COALESCE(SUM(CASE WHEN v.hours_known=1 THEN v.hours*v.quantity ELSE 0 END),0) knownHours,
      COALESCE(SUM(CASE WHEN v.hours_known=0 THEN v.quantity ELSE 0 END),0) tbdAssignments,
      COALESCE(SUM(v.quantity),0) assignments,
      CASE WHEN cm.program_count=1 THEN cm.single_program WHEN cm.program_count>1 THEN 'Multiple Programs' ELSE 'Unmatched' END attribution,
      COALESCE(cm.program_count,0) programCount
    FROM volunteer_slots v LEFT JOIN cm ON LOWER(v.volunteer_email)=cm.email
    WHERE v.status='filled' GROUP BY LOWER(COALESCE(v.volunteer_email,v.volunteer_name)) ORDER BY knownHours DESC,name LIMIT 200`).all<any>();
  const programs=await env.DB.prepare(`
    WITH cm AS (SELECT LOWER(email) email,COUNT(DISTINCT program) program_count,MIN(program) program FROM contact_mappings GROUP BY LOWER(email)),
    vh AS (SELECT LOWER(volunteer_email) email,SUM(CASE WHEN hours_known=1 THEN hours*quantity ELSE 0 END) known_hours,SUM(CASE WHEN hours_known=0 THEN quantity ELSE 0 END) tbd_assignments FROM volunteer_slots WHERE status='filled' AND volunteer_email IS NOT NULL GROUP BY LOWER(volunteer_email))
    SELECT cm.program name,COUNT(*) volunteers,COALESCE(SUM(vh.known_hours),0) knownHours,COALESCE(SUM(vh.tbd_assignments),0) tbdAssignments
    FROM cm JOIN vh ON vh.email=cm.email WHERE cm.program_count=1 GROUP BY cm.program ORDER BY knownHours DESC,name`).all<any>();
  const match=await env.DB.prepare(`WITH cm AS (SELECT LOWER(email) email,COUNT(DISTINCT program) pc FROM contact_mappings GROUP BY LOWER(email)), v AS (SELECT DISTINCT LOWER(volunteer_email) email FROM volunteer_slots WHERE status='filled' AND volunteer_email IS NOT NULL) SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN cm.pc=1 THEN 1 ELSE 0 END),0) matched,COALESCE(SUM(CASE WHEN cm.pc>1 THEN 1 ELSE 0 END),0) ambiguous,COALESCE(SUM(CASE WHEN cm.pc IS NULL THEN 1 ELSE 0 END),0) unmatched FROM v LEFT JOIN cm ON cm.email=v.email`).first<any>();
  const contacts=await env.DB.prepare("SELECT COUNT(*) mappings,COUNT(DISTINCT LOWER(email)) uniqueEmails FROM contact_mappings").first<any>();
  const unmatched=await env.DB.prepare(`WITH cm AS (SELECT LOWER(email) email,COUNT(DISTINCT program) pc,GROUP_CONCAT(DISTINCT program) programs FROM contact_mappings GROUP BY LOWER(email)) SELECT COALESCE(NULLIF(v.volunteer_name,''),v.volunteer_email,'Unknown') name,v.volunteer_email email,COALESCE(cm.programs,'') programs,COALESCE(cm.pc,0) programCount,SUM(CASE WHEN v.hours_known=1 THEN v.hours*v.quantity ELSE 0 END) knownHours,SUM(CASE WHEN v.hours_known=0 THEN v.quantity ELSE 0 END) tbdAssignments FROM volunteer_slots v LEFT JOIN cm ON LOWER(v.volunteer_email)=cm.email WHERE v.status='filled' AND (cm.pc IS NULL OR cm.pc<>1) GROUP BY LOWER(COALESCE(v.volunteer_email,v.volunteer_name)) ORDER BY knownHours DESC,name LIMIT 100`).all<any>();
  return {settings:cfg,summary:{hoursNeeded:needed,hoursFilled:filled,hoursRemaining:Math.max(0,needed-filled),knownHoursNeeded:knownNeeded,knownHoursFilled:knownFilled,estimatedHoursNeeded:Number(s?.tbdNeededQty||0)*est,estimatedHoursFilled:Number(s?.tbdFilledQty||0)*est,fillRate:needed?filled/needed*100:0,activeEvents:e.results.length,totalAssignments:Number(s?.totalAssignments||0),openSlots:Number(s?.openSlots||0),assignedSlots:Number(s?.assignedSlots||0),tbdAssignments:Number(s?.tbdAssignments||0),lastSyncAt:l?.syncTime||null,lastSyncStatus:l?.status||null,contactSyncAt:cl?.syncTime||null,contactSyncStatus:cl?.status||null,contactMappings:Number(contacts?.mappings||0),uniqueContactEmails:Number(contacts?.uniqueEmails||0),matchedVolunteers:Number(match?.matched||0),ambiguousVolunteers:Number(match?.ambiguous||0),unmatchedVolunteers:Number(match?.unmatched||0),volunteerEmails:Number(match?.total||0)},programs:(programs.results||[]).map((x:any)=>({...x,knownHours:Number(x.knownHours||0),tbdAssignments:Number(x.tbdAssignments||0),volunteers:Number(x.volunteers||0)})),events:e.results.map((x:any)=>({...x,hoursNeeded:Number(x.knownNeeded||0)+Number(x.tbdQty||0)*est,hoursFilled:Number(x.knownFilled||0)+Number(x.tbdFilledQty||0)*est})),volunteers:volunteers.results,unmatched:unmatched.results};
}
