import type{Env}from"./types";import{dashboard}from"./db";import{sync}from"./signupgenius";const SCHEMA = "CREATE TABLE IF NOT EXISTS programs(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE,required_hours REAL NOT NULL DEFAULT 0,color TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')));\nCREATE TABLE IF NOT EXISTS families(id INTEGER PRIMARY KEY AUTOINCREMENT,parent_name TEXT,parent_email TEXT UNIQUE,secondary_email TEXT,phone TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')));\nCREATE TABLE IF NOT EXISTS students(id INTEGER PRIMARY KEY AUTOINCREMENT,family_id INTEGER,student_name TEXT NOT NULL,program_id INTEGER,graduation_year INTEGER,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(family_id) REFERENCES families(id),FOREIGN KEY(program_id) REFERENCES programs(id));\nCREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,signupgenius_id TEXT NOT NULL UNIQUE,title TEXT NOT NULL,event_date TEXT,location TEXT,raw_json TEXT,updated_at TEXT NOT NULL DEFAULT(datetime('now')),created_at TEXT NOT NULL DEFAULT(datetime('now')));\nCREATE TABLE IF NOT EXISTS volunteer_slots(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL,signupgenius_slot_id TEXT NOT NULL UNIQUE,title TEXT NOT NULL,slot_date TEXT,start_time TEXT,end_time TEXT,hours REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'unknown',volunteer_name TEXT,volunteer_email TEXT,raw_json TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE);\nCREATE TABLE IF NOT EXISTS sync_log(id INTEGER PRIMARY KEY AUTOINCREMENT,sync_time TEXT NOT NULL,records INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL,message TEXT);\nCREATE INDEX IF NOT EXISTS idx_slots_event ON volunteer_slots(event_id);\nCREATE INDEX IF NOT EXISTS idx_slots_email ON volunteer_slots(volunteer_email);\nINSERT OR IGNORE INTO programs(name,required_hours) VALUES('Guard',0),('Percussion',0),('Winds',0),('Band Boosters',0);";
let schemaReady: Promise<void> | null = null;
async function ensureSchema(env:Env){
  if(!schemaReady) schemaReady=(async()=>{
    for(const statement of SCHEMA.split(";").map(x=>x.trim()).filter(Boolean)){
      await env.DB.prepare(statement).run();
    }
  })();
  await schemaReady;
}
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});async function run(env:Env){await ensureSchema(env);const t=new Date().toISOString();try{const r=await sync(env);await env.DB.prepare("INSERT INTO sync_log(sync_time,records,status,message) VALUES(?,?,?,?)").bind(t,r.slots,"success",`Synced ${r.events} events and ${r.slots} slots.`).run();return r}catch(e){const m=e instanceof Error?e.message:String(e);await env.DB.prepare("INSERT INTO sync_log(sync_time,records,status,message) VALUES(?,?,?,?)").bind(t,0,"error",m.slice(0,2000)).run();throw e}}export default{async fetch(req:Request,env:Env){const u=new URL(req.url);try{await ensureSchema(env);if(u.pathname==="/api/health")return json({ok:true});if(u.pathname==="/api/dashboard")return json(await dashboard(env));if(u.pathname==="/api/sync"&&req.method==="POST"){if(!env.SIGNUPGENIUS_API_KEY)return json({error:"SIGNUPGENIUS_API_KEY is not configured."},500);const r=await run(env);return json({ok:true,message:`Sync complete: ${r.events} events and ${r.slots} slots.`})}if(u.pathname.startsWith("/api/"))return json({error:"Not found"},404);return env.ASSETS.fetch(req)}catch(e){return json({error:e instanceof Error?e.message:"Unexpected server error"},500)}},async scheduled(_c,env){if(env.SIGNUPGENIUS_API_KEY)await run(env)}};