import type{Env}from"./types";
const rec=(x:unknown):Record<string,any>=>x&&typeof x==="object"&&!Array.isArray(x)?x as Record<string,any>:{};
const str=(o:Record<string,any>,keys:string[])=>{for(const k of keys){if(typeof o[k]==="string"&&o[k].trim())return o[k].trim();if(typeof o[k]==="number")return String(o[k])}return null};
export const arr=(x:unknown):unknown[]=>{if(Array.isArray(x))return x;const o=rec(x);for(const k of["data","results","signups","signup","items","slots","reports","report","rows","records"]){if(Array.isArray(o[k]))return o[k];if(o[k]&&typeof o[k]==="object"){const a=arr(o[k]);if(a.length)return a}}return[]};
export async function apiGet(env:Env,path:string){const u=new URL(`${(env.SIGNUPGENIUS_API_BASE||"https://api.signupgenius.com/v2/k/").replace(/\/+$/,"" )}/${path.replace(/^\/+/,"")}`);u.searchParams.set("user_key",env.SIGNUPGENIUS_API_KEY);const r=await fetch(u,{headers:{Accept:"application/json"}});const t=await r.text();if(!r.ok)throw Error(`SignUpGenius API ${r.status}: ${t.slice(0,400)}`);return JSON.parse(t)}
function txt(o:Record<string,any>,k:string){const v=o[k];return v===null||v===undefined?"":String(v).trim()}
function volunteer(o:Record<string,any>){const first=txt(o,"firstname"),last=txt(o,"lastname");const name=[first,last].filter(Boolean).join(" ")||txt(o,"name");return{name,email:txt(o,"email")}}
function quantity(o:Record<string,any>){const n=Number(o.myqty??o.quantity??1);return Number.isFinite(n)&&n>0?Math.round(n):1}
function duration(o:Record<string,any>){const start=Number(o.startdate||0),end=Number(o.enddate||0);if(start>0&&end>start)return{hours:(end-start)/3600,known:true};return{hours:0,known:false}}
function rowId(eid:string,o:Record<string,any>,i:number){const member=txt(o,"itemmemberid");if(member)return`${eid}:member:${member}`;const slot=txt(o,"slotitemid");if(slot)return`${eid}:open:${slot}`;return`${eid}:row:${i}`}
function slotDate(o:Record<string,any>){return txt(o,"startdatestring")||txt(o,"startdate")}
function slotStart(o:Record<string,any>){return txt(o,"startdatestring")||txt(o,"starttime")}
function slotEnd(o:Record<string,any>){return txt(o,"enddatestring")||txt(o,"endtime")}
export async function sync(env:Env){const events=arr(await apiGet(env,"/signups/created/active/"));let rows=0,filledQty=0,openQty=0,tbdQty=0;for(let i=0;i<events.length;i++){const e=rec(events[i]);const eid=str(e,["signupid","signupId","id","signup_id"])||`unknown-${i}`;const title=str(e,["title","name","signup_title","signupTitle"])||`SignUpGenius ${eid}`;await env.DB.prepare(`INSERT INTO events(signupgenius_id,title,event_date,location,raw_json,updated_at) VALUES(?,?,?,?,?,datetime('now')) ON CONFLICT(signupgenius_id) DO UPDATE SET title=excluded.title,event_date=excluded.event_date,location=excluded.location,raw_json=excluded.raw_json,updated_at=datetime('now')`).bind(eid,title,str(e,["date","event_date","eventDate","start_date","startDate"]),str(e,["location","event_location","eventLocation"]),JSON.stringify(events[i])).run();const db=await env.DB.prepare("SELECT id FROM events WHERE signupgenius_id=?").bind(eid).first<{id:number}>();if(!db)continue;const report=arr(await apiGet(env,`/signups/report/all/${encodeURIComponent(eid)}/`));await env.DB.prepare("DELETE FROM volunteer_slots WHERE event_id=?").bind(db.id).run();for(let j=0;j<report.length;j++){const s=rec(report[j]);const v=volunteer(s);const status=v.name||v.email||txt(s,"itemmemberid")?"filled":"open";const q=quantity(s);const d=duration(s);const sid=rowId(eid,s,j);await env.DB.prepare(`INSERT INTO volunteer_slots(event_id,signupgenius_slot_id,title,slot_date,start_time,end_time,hours,status,volunteer_name,volunteer_email,raw_json,quantity,hours_known) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(signupgenius_slot_id) DO UPDATE SET event_id=excluded.event_id,title=excluded.title,slot_date=excluded.slot_date,start_time=excluded.start_time,end_time=excluded.end_time,hours=excluded.hours,status=excluded.status,volunteer_name=excluded.volunteer_name,volunteer_email=excluded.volunteer_email,raw_json=excluded.raw_json,quantity=excluded.quantity,hours_known=excluded.hours_known,updated_at=datetime('now')`).bind(db.id,sid,txt(s,"item")||"Volunteer Slot",slotDate(s),slotStart(s),slotEnd(s),d.hours,status,v.name||null,v.email||null,JSON.stringify(s),q,d.known?1:0).run();rows++;if(status==="filled")filledQty+=q;else openQty+=q;if(!d.known)tbdQty+=q}}
return{events:events.length,rows,filledQty,openQty,tbdQty}}
