import { useEffect, useState } from "react";
import "./styles.css";

type Settings={estimateUntimedEnabled:boolean;estimateUntimedHours:number};
type Summary={hoursNeeded:number;hoursFilled:number;hoursRemaining:number;knownHoursNeeded:number;knownHoursFilled:number;estimatedHoursNeeded:number;estimatedHoursFilled:number;fillRate:number;activeEvents:number;totalAssignments:number;openSlots:number;assignedSlots:number;tbdAssignments:number;lastSyncAt:string|null;lastSyncStatus:string|null;contactSyncAt:string|null;contactSyncStatus:string|null;contactMappings:number;uniqueContactEmails:number;matchedVolunteers:number;ambiguousVolunteers:number;unmatchedVolunteers:number;volunteerEmails:number};
type Program={name:string;knownHours:number;tbdAssignments:number;volunteers:number};
type Event={id:number;signupgeniusId:string;title:string;eventDate:string|null;location:string|null;hoursNeeded:number;hoursFilled:number;knownNeeded:number;knownFilled:number;tbdQty:number;openSlots:number;assignedSlots:number};
type Volunteer={name:string;email:string|null;knownHours:number;tbdAssignments:number;assignments:number;attribution:string;programCount:number};
type Unmatched={name:string;email:string|null;programs:string;programCount:number;knownHours:number;tbdAssignments:number};
const fmt=(n:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:1}).format(n);
const date=(s:string|null)=>s?new Intl.DateTimeFormat("en-US",{dateStyle:"medium"}).format(new Date(s)):"—";
const programsLabel=(s:string)=>s.split(",").join(" • ");
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()||"").join("")||"V";
const programNames=(s:string)=>s.split(",").map(x=>x.trim()).filter(Boolean);
function Bar({v}:{v:number}){return <div className="bar"><i style={{width:`${Math.min(100,Math.max(0,v))}%`}}/></div>}
export default function App(){
 const[s,setS]=useState<Summary|null>(null),[p,setP]=useState<Program[]>([]),[e,setE]=useState<Event[]>([]),[v,setV]=useState<Volunteer[]>([]),[u,setU]=useState<Unmatched[]>([]),[settings,setSettings]=useState<Settings>({estimateUntimedEnabled:false,estimateUntimedHours:6}),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[contactSyncing,setContactSyncing]=useState(false),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const[draftStart,setDraftStart]=useState(""),[draftEnd,setDraftEnd]=useState(""),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState("");
 async function load(start=startDate,end=endDate){try{setErr("");const q=new URLSearchParams();if(start)q.set("start",start);if(end)q.set("end",end);const r=await fetch(`/api/dashboard${q.size?`?${q}`:""}`);const d=await r.json();if(!r.ok)throw Error(d.error);setS(d.summary);setP(d.programs||[]);setE(d.events||[]);setV(d.volunteers||[]);setU(d.unmatched||[]);setSettings(d.settings)}catch(x){setErr(x instanceof Error?x.message:"Unable to load dashboard")}finally{setLoading(false)}}
 async function run(){setSyncing(true);setMsg("");setErr("");try{const r=await fetch("/api/sync",{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg(d.message);await load()}catch(x){setErr(x instanceof Error?x.message:"Sync failed")}finally{setSyncing(false)}}
 async function syncContactsOnly(){setContactSyncing(true);setMsg("");setErr("");try{const r=await fetch("/api/contacts/sync",{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg(d.message);await load()}catch(x){setErr(x instanceof Error?x.message:"Contact sync failed")}finally{setContactSyncing(false)}}
 async function saveSettings(){setSaving(true);setMsg("");setErr("");try{const r=await fetch("/api/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(settings)});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg(settings.estimateUntimedEnabled?`Untimed assignments are estimated at ${settings.estimateUntimedHours} hours each.`:"Untimed assignments are excluded from hour totals and shown as TBD.");await load()}catch(x){setErr(x instanceof Error?x.message:"Unable to save settings")}finally{setSaving(false)}}
 function applyRange(){if(draftStart&&draftEnd&&draftStart>draftEnd){setErr("Start date cannot be after end date.");return}setStartDate(draftStart);setEndDate(draftEnd);setLoading(true);load(draftStart,draftEnd)}
 function clearRange(){setDraftStart("");setDraftEnd("");setStartDate("");setEndDate("");setLoading(true);load("","")}
 useEffect(()=>{load("","")},[]);if(loading)return <div className="center">Loading Volunteer Dashboard…</div>;
 const estimate=settings.estimateUntimedEnabled,totalProgramHours=p.reduce((a,x)=>a+Number(x.knownHours||0),0),matchedPct=s?.volunteerEmails?((s.matchedVolunteers/s.volunteerEmails)*100):0;
 const rangeLabel=startDate||endDate?`${startDate||"Beginning"} through ${endDate||"Present"}`:"All synchronized dates";
 return <div className="shell"><aside><div className="brand"><b>V</b><span>Volunteer<br/><small>Dashboard</small></span></div><nav><a className="active">Dashboard</a><a href="#programs">Programs</a><a href="#events">Events</a><a href="#volunteers">Volunteers</a><a href="#review">Unmatched</a></nav><div className="sidebarThanks"><span className="heart">♥</span><strong>Thank you, volunteers!</strong><small>Your time keeps every program moving forward.</small></div><div className="version"><strong>v0.3.1 visual refresh</strong><span>Multi-program hours split proportionally.</span></div></aside><main>
 <header><div><small>VOLUNTEER OPERATIONS</small><h1>Dashboard</h1><p className="subtitle">A clear view of volunteer demand, participation, and program credit.</p></div><div className="actions"><button className="secondary" onClick={syncContactsOnly} disabled={contactSyncing}>{contactSyncing?"Syncing contacts…":"Sync Contacts"}</button><button onClick={run} disabled={syncing}>{syncing?"Syncing…":"Sync All"}</button></div></header>
 <section className="rangePanel panel"><div><h2>Date Range</h2><p>All dashboard totals and attribution are limited to volunteer assignments whose start time falls in this range.</p></div><label>Start Date<input type="date" value={draftStart} onChange={x=>setDraftStart(x.target.value)}/></label><label>End Date<input type="date" value={draftEnd} onChange={x=>setDraftEnd(x.target.value)}/></label><button onClick={applyRange}>Apply Filter</button><button className="secondary" onClick={clearRange} disabled={!draftStart&&!draftEnd&&!startDate&&!endDate}>Clear</button><small className="rangeStatus">Showing: <b>{rangeLabel}</b></small></section>
 {msg&&<div className="notice ok">{msg}</div>}{err&&<div className="notice bad">{err}</div>}
 <section className="cards"><Card tone="violet" icon="H" l={estimate?"Hours Needed (incl. estimates)":"Known Hours Needed"} v={fmt(s?.hoursNeeded||0)} d={estimate?`${fmt(s?.estimatedHoursNeeded||0)} estimated`:`${s?.tbdAssignments||0} assignments still TBD`}/><Card tone="green" icon="✓" l={estimate?"Hours Filled (incl. estimates)":"Known Hours Filled"} v={fmt(s?.hoursFilled||0)} d={`${Math.round(s?.fillRate||0)}% of known/estimated demand`}/><Card tone="orange" icon="◷" l="Hours Remaining" v={fmt(s?.hoursRemaining||0)} d={`${s?.openSlots||0} open volunteer positions`}/><Card tone="blue" icon="P" l="Contact Match" v={`${Math.round(matchedPct)}%`} d={`${s?.matchedVolunteers||0} attributed · ${s?.unmatchedVolunteers||0} unmatched`}/><Card tone="indigo" icon="E" l="Active Events" v={String(s?.activeEvents||0)} d={`${s?.assignedSlots||0} filled · ${s?.totalAssignments||0} total positions`}/></section>
 <section className="coverage panel"><div><h2>Program Contact Attribution</h2><p>The <b>2026–2027 normalized parent roster</b> is embedded as the authoritative source. Multi-program volunteers automatically split their credit evenly across every represented program.</p></div><div className="coverageStats"><b>{s?.contactMappings||0}</b><span>roster mappings</span><b>{s?.uniqueContactEmails||0}</b><span>unique roster emails</span><b>{s?.ambiguousVolunteers||0}</b><span>multi-program volunteers in range</span><b>{s?.unmatchedVolunteers||0}</b><span>unmatched volunteers in range</span></div></section>
 <section className="estimate panel"><div><h2>Untimed Event Handling</h2><p>SignUpGenius returns no end time for events marked TBA. Keep them out of hour totals, or apply a planning estimate until final times are published.</p></div><label className="toggle"><input type="checkbox" checked={settings.estimateUntimedEnabled} onChange={x=>setSettings({...settings,estimateUntimedEnabled:x.target.checked})}/><span>Use estimate</span></label><label>Hours per TBD position<input type="number" min="0" max="24" step="0.5" value={settings.estimateUntimedHours} disabled={!settings.estimateUntimedEnabled} onChange={x=>setSettings({...settings,estimateUntimedHours:Number(x.target.value)})}/></label><button onClick={saveSettings} disabled={saving}>{saving?"Saving…":"Save"}</button></section>
 <section className="dashboardGrid"><div className="leftStack">
 <div className="panel featurePanel" id="programs"><div className="panelTitle"><span className="titleMark">P</span><div><h2>Program Participation</h2><p>Credit follows the program(s) represented by each volunteer—not the event worked. Two programs split 50/50; three programs split one-third each.</p></div></div>{p.length?p.map(x=>{const pct=totalProgramHours?x.knownHours/totalProgramHours*100:0;return <div className="program" key={x.name}><div><strong>{x.name}</strong><small>{x.volunteers} represented volunteers · {fmt(x.tbdAssignments)} TBD assignment credit</small></div><b>{fmt(x.knownHours)} hrs</b><span>{Math.round(pct)}%</span><Bar v={pct}/></div>}):<div className="empty">No program-attributed volunteer activity in this date range.</div>}</div>
 <div className="panel volunteers" id="volunteers"><div className="panelTitle"><span className="titleMark">V</span><div><h2>Volunteer Hours</h2><p>Known hours by volunteer with roster-based program attribution for the selected date range.</p></div></div><div className="volhead"><span>Volunteer</span><span>Program(s)</span><span>Known hours</span><span>Allocation</span><span>Assignments</span><span>Time TBD</span></div>{v.length?v.slice(0,80).map((x,i)=>{const names=programNames(x.attribution);const share=names.length?Number(x.knownHours||0)/names.length:0;return <div className="volrow" key={`${x.email||x.name}-${i}`}><div className="volIdentity"><span className="avatar">{initials(x.name)}</span><div><strong>{x.name}</strong>{x.email&&<small>{x.email}</small>}</div></div><div className="badgeWrap">{names.length?names.map(n=><span key={n} className="badge matched">{n}</span>):<span className="badge unmatched">Unmatched</span>}</div><b className="hoursValue">{fmt(Number(x.knownHours||0))}</b><div className="allocation">{names.length?names.map(n=><small key={n}>{n}: <b>{fmt(share)}h</b> ({Math.round(100/names.length)}%)</small>):<small>—</small>}</div><span>{x.assignments}</span><span>{x.tbdAssignments||0}</span></div>}):<div className="empty">No filled volunteer records in this date range.</div>}</div>
 </div><div className="panel eventsPanel" id="events"><div className="panelTitle"><span className="titleMark">E</span><div><h2>Active Events</h2><p>Only assignments starting in the selected date range are included. Quantity is honored.</p></div></div>{e.length?e.map(x=><div className="event" key={x.id}><strong>{x.title}</strong><small>{date(x.eventDate)} · {x.location||"Location not set"}</small><div className="nums"><span>{fmt(x.hoursFilled)} filled hrs</span><span>{fmt(x.hoursNeeded)} needed hrs</span><span>{x.openSlots} open</span>{x.tbdQty>0&&<span>{x.tbdQty} TBD</span>}</div><Bar v={x.hoursNeeded?x.hoursFilled/x.hoursNeeded*100:0}/></div>):<div className="empty">No synchronized assignments fall in this date range.</div>}</div></section>
 <section className="panel review" id="review"><div className="panelTitle"><span className="titleMark warning">!</span><div><h2>Needs Attribution Review</h2><p>Only volunteers with no email match in the normalized parent roster appear here. Multi-program volunteers are automatically split and do not require review.</p></div></div>{u.length?<><div className="reviewhead"><span>Volunteer</span><span>Roster match</span><span>Known hours</span><span>TBD</span></div>{u.slice(0,80).map((x,i)=><div className="reviewrow" key={`${x.email||x.name}-${i}`}><div><strong>{x.name}</strong><small>{x.email||"No email"}</small></div><span>No roster match</span><b>{fmt(Number(x.knownHours||0))}</b><span>{x.tbdAssignments||0}</span></div>)}</>:<div className="empty">No volunteers require attribution review in this date range.</div>}</section>
 <section className="panel methodology"><h2>v0.3.1 Attribution Rules</h2><p><b>Roster:</b> embedded normalized 2026–2027 Parent Contacts. <b>Sync:</b> contacts are written to D1 in batches to avoid Worker subrequest limits. <b>Matching:</b> email is case-insensitive. <b>Credit:</b> one program gets 100%; two get 50% each; three get 33.3% each. <b>Date filter:</b> totals use each SignUpGenius assignment's start timestamp. <b>Review:</b> only emails absent from the roster remain unmatched.</p></section>
 <footer><span>SignUpGenius sync: {date(s?.lastSyncAt||null)} · Contact sync: {date(s?.contactSyncAt||null)}</span><span>SignUpGenius + Embedded Normalized Parent Roster → Cloudflare D1</span></footer>
 </main></div>
}
function Card({l,v,d,icon,tone}:{l:string;v:string;d:string;icon:string;tone:string}){return <div className={`card tone-${tone}`}><div className="cardTop"><span className="metricIcon">{icon}</span><small>{l}</small></div><strong>{v}</strong><span>{d}</span></div>}
