import { useEffect, useMemo, useState } from "react";
import "./styles.css";

type Settings={estimateUntimedEnabled:boolean;estimateUntimedHours:number};
type Summary={hoursNeeded:number;hoursFilled:number;hoursRemaining:number;knownHoursNeeded:number;knownHoursFilled:number;estimatedHoursNeeded:number;estimatedHoursFilled:number;fillRate:number;activeEvents:number;totalAssignments:number;openSlots:number;assignedSlots:number;tbdAssignments:number;lastSyncAt:string|null;lastSyncStatus:string|null;contactSyncAt:string|null;contactSyncStatus:string|null;contactMappings:number;uniqueContactEmails:number;manualOverrideEmails:number;manualOverrideMappings:number;matchedVolunteers:number;ambiguousVolunteers:number;unmatchedVolunteers:number;volunteerEmails:number};
type Program={name:string;knownHours:number;tbdAssignments:number;volunteers:number;volunteerCredits:number};
type Event={id:number;signupgeniusId:string;title:string;eventDate:string|null;location:string|null;hoursNeeded:number;hoursFilled:number;knownNeeded:number;knownFilled:number;tbdQty:number;openSlots:number;assignedSlots:number};
type Volunteer={name:string;email:string|null;knownHours:number;tbdAssignments:number;assignments:number;attribution:string;programCount:number;manualOverride:number};
type Unmatched={name:string;email:string|null;programs:string;programCount:number;knownHours:number;tbdAssignments:number};
const fmt=(n:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:1}).format(n);
const date=(s:string|null)=>s?new Intl.DateTimeFormat("en-US",{dateStyle:"medium"}).format(new Date(s)):"—";
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()||"").join("")||"V";
const programNames=(s:string)=>s==="Unmatched"?[]:s.split(",").map(x=>x.trim()).filter(Boolean);
const COLORS=["#2f6fdd","#6f55d9","#e18732","#159aa5","#2a9b63","#c95d7b","#6a7b91","#b59028"];
function Bar({v}:{v:number}){return <div className="bar"><i style={{width:`${Math.min(100,Math.max(0,v))}%`}}/></div>}

export default function App(){
 const[s,setS]=useState<Summary|null>(null),[p,setP]=useState<Program[]>([]),[e,setE]=useState<Event[]>([]),[v,setV]=useState<Volunteer[]>([]),[u,setU]=useState<Unmatched[]>([]),[availablePrograms,setAvailablePrograms]=useState<string[]>([]),[settings,setSettings]=useState<Settings>({estimateUntimedEnabled:false,estimateUntimedHours:6}),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[contactSyncing,setContactSyncing]=useState(false),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const[draftStart,setDraftStart]=useState(""),[draftEnd,setDraftEnd]=useState(""),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState("");
 const[editingEmail,setEditingEmail]=useState<string|null>(null),[selectedPrograms,setSelectedPrograms]=useState<string[]>([]),[overrideSaving,setOverrideSaving]=useState(false);
 async function load(start=startDate,end=endDate){try{setErr("");const q=new URLSearchParams();if(start)q.set("start",start);if(end)q.set("end",end);const r=await fetch(`/api/dashboard${q.size?`?${q}`:""}`);const d=await r.json();if(!r.ok)throw Error(d.error);setS(d.summary);setP(d.programs||[]);setE(d.events||[]);setV(d.volunteers||[]);setU(d.unmatched||[]);setAvailablePrograms(d.availablePrograms||[]);setSettings(d.settings)}catch(x){setErr(x instanceof Error?x.message:"Unable to load dashboard")}finally{setLoading(false)}}
 async function run(){setSyncing(true);setMsg("");setErr("");try{const r=await fetch("/api/sync",{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg(d.message);await load()}catch(x){setErr(x instanceof Error?x.message:"Sync failed")}finally{setSyncing(false)}}
 async function syncContactsOnly(){setContactSyncing(true);setMsg("");setErr("");try{const r=await fetch("/api/contacts/sync",{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg(d.message);await load()}catch(x){setErr(x instanceof Error?x.message:"Contact sync failed")}finally{setContactSyncing(false)}}
 async function saveSettings(){setSaving(true);setMsg("");setErr("");try{const r=await fetch("/api/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(settings)});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg(settings.estimateUntimedEnabled?`Untimed assignments are estimated at ${settings.estimateUntimedHours} hours each.`:"Untimed assignments are excluded from hour totals and shown as TBD.");await load()}catch(x){setErr(x instanceof Error?x.message:"Unable to save settings")}finally{setSaving(false)}}
 async function saveOverride(person:Unmatched){if(!person.email)return;setOverrideSaving(true);setErr("");setMsg("");try{const r=await fetch("/api/attribution/override",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:person.email,name:person.name,programs:selectedPrograms})});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg(d.message);setEditingEmail(null);setSelectedPrograms([]);await load()}catch(x){setErr(x instanceof Error?x.message:"Unable to save manual program assignment")}finally{setOverrideSaving(false)}}
 function applyRange(){if(draftStart&&draftEnd&&draftStart>draftEnd){setErr("Start date cannot be after end date.");return}setStartDate(draftStart);setEndDate(draftEnd);setLoading(true);load(draftStart,draftEnd)}
 function clearRange(){setDraftStart("");setDraftEnd("");setStartDate("");setEndDate("");setLoading(true);load("","")}
 function toggleProgram(program:string){setSelectedPrograms(x=>x.includes(program)?x.filter(y=>y!==program):[...x,program])}
 useEffect(()=>{load("","")},[]);
 const totalProgramHours=p.reduce((a,x)=>a+Number(x.knownHours||0),0),totalVolunteerCredits=p.reduce((a,x)=>a+Number(x.volunteerCredits||0),0),matchedPct=s?.volunteerEmails?((s.matchedVolunteers/s.volunteerEmails)*100):0;
 const rangeLabel=startDate||endDate?`${startDate||"Beginning"} through ${endDate||"Present"}`:"All synchronized dates";
 const donut=useMemo(()=>{let cursor=0;const parts=p.map((x,i)=>{const pct=totalVolunteerCredits?x.volunteerCredits/totalVolunteerCredits*100:0;const start=cursor;cursor+=pct;return `${COLORS[i%COLORS.length]} ${start}% ${cursor}%`});return parts.length?`conic-gradient(${parts.join(",")})`:"#e8edf5"},[p,totalVolunteerCredits]);
 if(loading)return <div className="center">Loading Volunteer Dashboard…</div>;
 return <div className="shell"><aside><div className="brand brandLogo"><img src="/boosters-logo.png" alt="Miamisburg Band and Guard Boosters logo"/><span>Volunteer<br/><small>Dashboard</small></span></div><nav><a className="active">Dashboard</a><a href="#visuals">Insights</a><a href="#programs">Programs</a><a href="#events">Events</a><a href="#volunteers">Volunteers</a><a href="#review">Unmatched</a></nav><div className="sidebarThanks"><span className="heart">♥</span><strong>Thank you, volunteers!</strong><small>Your time keeps every program moving forward.</small></div><div className="version"><strong>v0.3.3 visual refinement</strong><span>Manual overrides · proportional credit · date filtering</span></div></aside><main>
 <header><div><small>MIAMISBURG BAND &amp; GUARD BOOSTERS</small><h1>Volunteer Operations</h1><p className="subtitle">Participation, program credit, volunteer mix, and performance in one view.</p></div><div className="actions"><button className="secondary" onClick={syncContactsOnly} disabled={contactSyncing}>{contactSyncing?"Syncing contacts…":"Sync Contacts"}</button><button onClick={run} disabled={syncing}>{syncing?"Syncing…":"Sync All"}</button></div></header>
 <section className="rangePanel panel"><div><h2>Date Range</h2><p>All totals, program credit, and visualizations use assignments whose start time falls in this range.</p></div><label>Start Date<input type="date" value={draftStart} onChange={x=>setDraftStart(x.target.value)}/></label><label>End Date<input type="date" value={draftEnd} onChange={x=>setDraftEnd(x.target.value)}/></label><button onClick={applyRange}>Apply Filter</button><button className="secondary" onClick={clearRange} disabled={!draftStart&&!draftEnd&&!startDate&&!endDate}>Clear</button><small className="rangeStatus">Showing: <b>{rangeLabel}</b></small></section>
 {msg&&<div className="notice ok">{msg}</div>}{err&&<div className="notice bad">{err}</div>}
 <section className="cards"><Card tone="violet" icon="H" l={settings.estimateUntimedEnabled?"Hours Needed (incl. estimates)":"Known Hours Needed"} v={fmt(s?.hoursNeeded||0)} d={`${s?.tbdAssignments||0} assignments still TBD`}/><Card tone="green" icon="✓" l="Hours Filled" v={fmt(s?.hoursFilled||0)} d={`${Math.round(s?.fillRate||0)}% of known/estimated demand`}/><Card tone="orange" icon="◷" l="Hours Remaining" v={fmt(s?.hoursRemaining||0)} d={`${s?.openSlots||0} open volunteer positions`}/><Card tone="blue" icon="P" l="Contact Match" v={`${Math.round(matchedPct)}%`} d={`${s?.matchedVolunteers||0} attributed · ${s?.unmatchedVolunteers||0} unmatched`}/><Card tone="indigo" icon="E" l="Active Events" v={String(s?.activeEvents||0)} d={`${s?.assignedSlots||0} filled · ${s?.totalAssignments||0} total positions`}/></section>
 <section className="visualGrid" id="visuals"><div className="panel insightPanel"><div className="panelTitle"><span className="titleMark">M</span><div><h2>Volunteer Mix</h2><p>Program representation using fractional volunteer credit. A volunteer tied to two programs contributes 0.5 to each.</p></div></div><div className="mixBody"><div className="donut" style={{background:donut}}><div><strong>{fmt(totalVolunteerCredits)}</strong><span>volunteer equivalents</span></div></div><div className="mixLegend">{p.map((x,i)=>{const pct=totalVolunteerCredits?x.volunteerCredits/totalVolunteerCredits*100:0;return <div className="legendRow" key={x.name}><i style={{background:COLORS[i%COLORS.length]}}/><span>{x.name}</span><b>{fmt(x.volunteerCredits)}</b><em>{Math.round(pct)}%</em></div>})}</div></div></div>
 <div className="panel insightPanel"><div className="panelTitle"><span className="titleMark rank">#</span><div><h2>Program Performance Ranking</h2><p>Highest to lowest based on credited volunteer hours in the selected date range.</p></div></div><div className="ranking">{p.map((x,i)=>{const max=p[0]?.knownHours||1;return <div className="rankRow" key={x.name}><span className={`rankNo ${i<3?`top${i+1}`:""}`}>{i+1}</span><div><div className="rankLabel"><strong>{x.name}</strong><b>{fmt(x.knownHours)} hrs</b></div><Bar v={x.knownHours/max*100}/><small>{totalProgramHours?Math.round(x.knownHours/totalProgramHours*100):0}% of all credited hours</small></div></div>})}</div></div></section>
 <section className="coverage panel"><div><h2>Program Contact Attribution</h2><p>The <b>2026–2027 normalized parent roster</b> is the default source. Manual assignments override the roster for that email, and multi-program volunteers split credit evenly.</p></div><div className="coverageStats"><b>{s?.contactMappings||0}</b><span>roster mappings</span><b>{s?.manualOverrideEmails||0}</b><span>manual overrides</span><b>{s?.ambiguousVolunteers||0}</b><span>multi-program volunteers in range</span><b>{s?.unmatchedVolunteers||0}</b><span>unmatched volunteers in range</span></div></section>
 <section className="estimate panel"><div><h2>Untimed Event Handling</h2><p>Keep TBA assignments out of hour totals, or apply a planning estimate until final times are published.</p></div><label className="toggle"><input type="checkbox" checked={settings.estimateUntimedEnabled} onChange={x=>setSettings({...settings,estimateUntimedEnabled:x.target.checked})}/><span>Use estimate</span></label><label>Hours per TBD position<input type="number" min="0" max="24" step="0.5" value={settings.estimateUntimedHours} disabled={!settings.estimateUntimedEnabled} onChange={x=>setSettings({...settings,estimateUntimedHours:Number(x.target.value)})}/></label><button onClick={saveSettings} disabled={saving}>{saving?"Saving…":"Save"}</button></section>
 <section className="overviewGrid"><div className="panel featurePanel" id="programs"><div className="panelTitle"><span className="titleMark">P</span><div><h2>Program Participation</h2><p>Credit follows the program(s) represented by each volunteer—not the event worked.</p></div></div>{p.length?p.map(x=>{const pct=totalProgramHours?x.knownHours/totalProgramHours*100:0;return <div className="program" key={x.name}><div><strong>{x.name}</strong><small>{fmt(x.volunteerCredits)} volunteer equivalents · {fmt(x.tbdAssignments)} TBD assignment credit</small></div><b>{fmt(x.knownHours)} hrs</b><span>{Math.round(pct)}%</span><Bar v={pct}/></div>}):<div className="empty">No program-attributed activity in this date range.</div>}</div>
 <div className="panel eventsPanel" id="events"><div className="panelTitle"><span className="titleMark">E</span><div><h2>Active Events</h2><p>Only assignments starting in the selected date range are included.</p></div></div>{e.length?e.map(x=><div className="event" key={x.id}><strong>{x.title}</strong><small>{date(x.eventDate)} · {x.location||"Location not set"}</small><div className="nums"><span>{fmt(x.hoursFilled)} filled hrs</span><span>{fmt(x.hoursNeeded)} needed hrs</span><span>{x.openSlots} open</span>{x.tbdQty>0&&<span>{x.tbdQty} TBD</span>}</div><Bar v={x.hoursNeeded?x.hoursFilled/x.hoursNeeded*100:0}/></div>):<div className="empty">No synchronized assignments fall in this date range.</div>}</div></section>
 <section className="panel volunteers volunteerWide" id="volunteers"><div className="panelTitle volunteerTitle"><span className="titleMark">V</span><div><h2>Volunteer Hours</h2><p>Known hours with roster or manual program attribution. Multi-program allocations are shown alongside each total.</p></div><span className="recordCount">{v.length} volunteers in range</span></div><div className="volTableWrap"><div className="volhead"><span>Volunteer</span><span>Program(s)</span><span>Known hours</span><span>Allocation</span><span>Assignments</span><span>Time TBD</span></div>{v.length?v.slice(0,80).map((x,i)=>{const names=programNames(x.attribution);const share=names.length?Number(x.knownHours||0)/names.length:0;return <div className="volrow" key={`${x.email||x.name}-${i}`}><div className="volIdentity"><span className="avatar">{initials(x.name)}</span><div><strong>{x.name}</strong>{x.email&&<small>{x.email}{x.manualOverride?" · manual":""}</small>}</div></div><div className="badgeWrap">{names.length?names.map(n=><span key={n} className="badge matched">{n}</span>):<span className="badge unmatched">Unmatched</span>}</div><b className="hoursValue">{fmt(Number(x.knownHours||0))}</b><div className="allocation">{names.length?names.map(n=><small key={n}>{n}: <b>{fmt(share)}h</b> ({Math.round(100/names.length)}%)</small>):<small>—</small>}</div><span>{x.assignments}</span><span>{x.tbdAssignments||0}</span></div>}):<div className="empty">No filled volunteer records in this date range.</div>}</div></section>
 <section className="panel review" id="review"><div className="panelTitle"><span className="titleMark warning">!</span><div><h2>Unmatched Volunteer Assignment</h2><p>Assign one or more programs here. Saved assignments persist in D1 and override roster matching for that email.</p></div></div>{u.length?<div className="reviewList">{u.slice(0,80).map((x,i)=>{const open=editingEmail===x.email;return <div className="reviewItem" key={`${x.email||x.name}-${i}`}><div className="reviewSummary"><div className="volIdentity"><span className="avatar warningAvatar">{initials(x.name)}</span><div><strong>{x.name}</strong><small>{x.email||"No email available"}</small></div></div><span><b>{fmt(Number(x.knownHours||0))}</b> known hrs</span><span>{x.tbdAssignments||0} TBD</span><button className="secondary smallBtn" disabled={!x.email} onClick={()=>{setEditingEmail(open?null:x.email);setSelectedPrograms([])}}>{open?"Cancel":"Assign Program"}</button></div>{open&&<div className="assignmentEditor"><strong>Select every program this volunteer represents</strong><div className="programChecks">{availablePrograms.map(program=><label key={program}><input type="checkbox" checked={selectedPrograms.includes(program)} onChange={()=>toggleProgram(program)}/><span>{program}</span></label>)}</div><div className="editorActions"><small>{selectedPrograms.length===0?"Select at least one program.":`${selectedPrograms.length} program${selectedPrograms.length===1?"":"s"} selected; hours will split evenly.`}</small><button disabled={!selectedPrograms.length||overrideSaving} onClick={()=>saveOverride(x)}>{overrideSaving?"Saving…":"Save Assignment"}</button></div></div>}</div>})}</div>:<div className="empty successEmpty">✓ Every volunteer in this date range has a program attribution.</div>}</section>
 <section className="panel methodology"><h2>v0.3.3 Attribution Rules</h2><p><b>Priority:</b> manual override → normalized roster → unmatched. <b>Credit:</b> one program gets 100%; two get 50% each; three get 33.3% each. <b>Volunteer mix:</b> fractional volunteer equivalents. <b>Performance ranking:</b> credited volunteer hours, highest to lowest, within the selected date range.</p></section>
 <footer><span>SignUpGenius sync: {date(s?.lastSyncAt||null)} · Contact sync: {date(s?.contactSyncAt||null)}</span><span>SignUpGenius + Parent Roster + Manual Overrides → Cloudflare D1</span></footer>
 </main></div>
}
function Card({l,v,d,icon,tone}:{l:string;v:string;d:string;icon:string;tone:string}){return <div className={`card tone-${tone}`}><div className="cardTop"><span className="metricIcon">{icon}</span><small>{l}</small></div><strong>{v}</strong><span>{d}</span></div>}
